### ISSUE TITLE
componentWillReceiveProps has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by Victorien-Tardif** [oklas/react-through#4]
See https://fb.me/react-unsafe-component-lifecycles

**Comment by oklas** [comment]
Hi, using of `componentWillReceiveProps` is removed from v1.1.4. Only docs and test still have and need to be fixed. Let me know if I missed something, in actual library code. Thanks

**Comment by Victorien-Tardif** [comment]
Hi, no you are right, sorry!

**Comment by oklas** [comment]
Ok, feel free to create new ticket if any question or problem, subscribe fb/tw, new component Through is implemented but still not documented, need all your support, starts and so on
